import type { FormTheme } from "../schema";

export const FORM_THEME_PRESETS: ReadonlyArray<FormTheme> = [
  {
    presetId: "lab",
    primaryColor: "#3b82f6",
    accentColor: "#8b5cf6",
    backgroundColor: "#ffffff",
    textColor: "#0f172a",
    emoji: "🧪",
    showEmoji: true,
    borderRadius: "md",
    fontFamily: "sans",
    headingFontFamily: "sans",
    spacing: "normal",
    pattern: "dots",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
  },
  {
    presetId: "minimal",
    primaryColor: "#0f172a",
    accentColor: "#475569",
    backgroundColor: "#ffffff",
    textColor: "#0f172a",
    emoji: "📋",
    showEmoji: true,
    borderRadius: "none",
    fontFamily: "sans",
    headingFontFamily: "sans",
    spacing: "compact",
    pattern: "none",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
  },
  {
    presetId: "playful",
    primaryColor: "#ec4899",
    accentColor: "#f59e0b",
    backgroundColor: "#fef3c7",
    textColor: "#7c2d12",
    emoji: "🎨",
    showEmoji: true,
    borderRadius: "full",
    fontFamily: "rounded",
    headingFontFamily: "display",
    spacing: "relaxed",
    pattern: "waves",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "bounce",
    fieldEntranceAnimation: "scale-in",
    submitLabel: "¡Listo!",
    cardStyle: "elevated",
    showProgressBar: true,
  },
  {
    presetId: "dark",
    primaryColor: "#60a5fa",
    accentColor: "#a78bfa",
    backgroundColor: "#0f172a",
    textColor: "#f1f5f9",
    emoji: "🌙",
    showEmoji: true,
    borderRadius: "lg",
    fontFamily: "sans",
    headingFontFamily: "mono",
    spacing: "normal",
    pattern: "grid",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "pulse",
    fieldEntranceAnimation: "fade-up",
    submitLabel: "Enviar",
    cardStyle: "glass",
    showProgressBar: false,
  },
  {
    presetId: "academic",
    primaryColor: "#7c3aed",
    accentColor: "#4f46e5",
    backgroundColor: "#faf5ff",
    textColor: "#1e1b4b",
    emoji: "📚",
    showEmoji: true,
    borderRadius: "sm",
    fontFamily: "serif",
    headingFontFamily: "serif",
    spacing: "relaxed",
    pattern: "none",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
  },
  {
    presetId: "tropical",
    primaryColor: "#10b981",
    accentColor: "#06b6d4",
    backgroundColor: "#ecfdf5",
    textColor: "#064e3b",
    emoji: "🌴",
    showEmoji: true,
    borderRadius: "xl",
    fontFamily: "rounded",
    headingFontFamily: "rounded",
    spacing: "normal",
    pattern: "dots",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "confetti",
    fieldEntranceAnimation: "fade-up",
    submitLabel: "Enviar",
    cardStyle: "elevated",
    showProgressBar: true,
  },
  {
    presetId: "racing",
    primaryColor: "#dc2626",
    accentColor: "#facc15",
    backgroundColor: "#111827",
    textColor: "#f9fafb",
    emoji: "🏁",
    showEmoji: true,
    borderRadius: "lg",
    fontFamily: "display",
    headingFontFamily: "display",
    spacing: "normal",
    pattern: "checkered",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "race",
    fieldEntranceAnimation: "race-in",
    submitLabel: "¡A la carrera!",
    cardStyle: "glass",
    showProgressBar: true,
  },
  {
    presetId: "party",
    primaryColor: "#d946ef",
    accentColor: "#f97316",
    backgroundColor: "#4c1d95",
    textColor: "#ffffff",
    emoji: "🎈",
    showEmoji: true,
    borderRadius: "full",
    fontFamily: "rounded",
    headingFontFamily: "display",
    spacing: "relaxed",
    pattern: "stars",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "confetti",
    fieldEntranceAnimation: "flip-in",
    submitLabel: "¡Celebrar!",
    cardStyle: "elevated",
    showProgressBar: true,
  },
  {
    presetId: "neon",
    primaryColor: "#22d3ee",
    accentColor: "#e879f9",
    backgroundColor: "#020617",
    textColor: "#e2e8f0",
    emoji: "⚡",
    showEmoji: true,
    borderRadius: "lg",
    fontFamily: "mono",
    headingFontFamily: "display",
    spacing: "normal",
    pattern: "carbon",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "pulse",
    fieldEntranceAnimation: "slide-left",
    submitLabel: "Iniciar",
    cardStyle: "glass",
    showProgressBar: false,
  },
];

export function getPresetById(id: string): FormTheme | undefined {
  return FORM_THEME_PRESETS.find((preset) => preset.presetId === id);
}
